// Workout movement + muscle database (151 movements, 26 muscles).
// Source: workout-movements.json spec. Loaded as window.MOVEMENT_DB.
// Exercise muscle entries are [muscleId, contribution 0..1]; role derives from
// contribution: primary >=0.8, secondary >=0.4, stabilizer <0.4.
(function () {
  var M = {
    chest_upper: { name: 'Upper Chest', group: 'Chest' },
    chest_mid: { name: 'Mid Chest', group: 'Chest' },
    chest_lower: { name: 'Lower Chest', group: 'Chest' },
    lats: { name: 'Lats', group: 'Back' },
    traps_upper: { name: 'Upper Traps', group: 'Back' },
    traps_mid_lower: { name: 'Mid/Lower Traps', group: 'Back' },
    rhomboids: { name: 'Rhomboids', group: 'Back' },
    erectors: { name: 'Spinal Erectors', group: 'Back' },
    teres: { name: 'Teres Major', group: 'Back' },
    delts_front: { name: 'Front Delts', group: 'Shoulders' },
    delts_side: { name: 'Side Delts', group: 'Shoulders' },
    delts_rear: { name: 'Rear Delts', group: 'Shoulders' },
    rotator_cuff: { name: 'Rotator Cuff', group: 'Shoulders' },
    biceps: { name: 'Biceps', group: 'Arms' },
    brachialis: { name: 'Brachialis', group: 'Arms' },
    triceps: { name: 'Triceps', group: 'Arms' },
    forearms: { name: 'Forearms', group: 'Arms' },
    quads: { name: 'Quadriceps', group: 'Legs' },
    hamstrings: { name: 'Hamstrings', group: 'Legs' },
    glutes: { name: 'Glutes', group: 'Legs' },
    adductors: { name: 'Adductors', group: 'Legs' },
    abductors: { name: 'Abductors', group: 'Legs' },
    calves: { name: 'Calves', group: 'Legs' },
    abs: { name: 'Rectus Abdominis', group: 'Core' },
    obliques: { name: 'Obliques', group: 'Core' },
    hip_flexors: { name: 'Hip Flexors', group: 'Core' }
  };
  var PATTERNS = {
    squat: 'Squat', lunge: 'Lunge', hinge: 'Hinge',
    horizontal_push: 'Horizontal Push', vertical_push: 'Vertical Push',
    horizontal_pull: 'Horizontal Pull', vertical_pull: 'Vertical Pull',
    shoulder_iso: 'Shoulders', biceps: 'Biceps', triceps: 'Triceps',
    core: 'Core', calves: 'Calves', forearms: 'Forearms', carry: 'Carry'
  };
  var PATTERN_ORDER = ['horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull',
    'shoulder_iso', 'biceps', 'triceps', 'squat', 'lunge', 'hinge', 'calves', 'core', 'forearms', 'carry'];
  // [id, name, pattern, equipment, mechanic(c|i), [[muscle, contribution], ...]]
  var E = [
    ['barbell_back_squat', 'Barbell Back Squat', 'squat', 'barbell', 'c', [['quads', 1], ['glutes', .8], ['adductors', .5], ['erectors', .5], ['hamstrings', .25], ['abs', .25]]],
    ['barbell_front_squat', 'Barbell Front Squat', 'squat', 'barbell', 'c', [['quads', 1], ['glutes', .6], ['erectors', .5], ['abs', .5], ['adductors', .25]]],
    ['goblet_squat', 'Goblet Squat', 'squat', 'dumbbell', 'c', [['quads', 1], ['glutes', .6], ['abs', .5], ['adductors', .25]]],
    ['hack_squat', 'Hack Squat (machine)', 'squat', 'machine', 'c', [['quads', 1], ['glutes', .5], ['adductors', .25]]],
    ['leg_press', 'Leg Press', 'squat', 'machine', 'c', [['quads', 1], ['glutes', .6], ['adductors', .4], ['hamstrings', .25]]],
    ['box_squat', 'Box Squat', 'squat', 'barbell', 'c', [['quads', .9], ['glutes', .9], ['erectors', .5], ['hamstrings', .4]]],
    ['smith_squat', 'Smith Machine Squat', 'squat', 'machine', 'c', [['quads', 1], ['glutes', .6], ['adductors', .4]]],
    ['belt_squat', 'Belt Squat', 'squat', 'machine', 'c', [['quads', 1], ['glutes', .6], ['adductors', .4]]],
    ['pistol_squat', 'Pistol Squat', 'squat', 'bodyweight', 'c', [['quads', 1], ['glutes', .7], ['abs', .4], ['abductors', .4]]],
    ['sissy_squat', 'Sissy Squat', 'squat', 'bodyweight', 'i', [['quads', 1], ['hip_flexors', .3]]],
    ['leg_extension', 'Leg Extension', 'squat', 'machine', 'i', [['quads', 1]]],
    ['pendulum_squat', 'Pendulum Squat', 'squat', 'machine', 'c', [['quads', 1], ['glutes', .6], ['adductors', .3]]],
    ['v_squat', 'V-Squat Machine', 'squat', 'machine', 'c', [['quads', 1], ['glutes', .6], ['adductors', .3]]],
    ['reverse_hack_squat', 'Reverse Hack Squat', 'squat', 'machine', 'c', [['glutes', 1], ['quads', .7], ['hamstrings', .4]]],
    ['bulgarian_split_squat', 'Bulgarian Split Squat', 'lunge', 'dumbbell', 'c', [['quads', 1], ['glutes', .9], ['adductors', .4], ['hamstrings', .3], ['abductors', .3]]],
    ['walking_lunge', 'Walking Lunge', 'lunge', 'dumbbell', 'c', [['quads', .9], ['glutes', .9], ['hamstrings', .4], ['adductors', .3]]],
    ['reverse_lunge', 'Reverse Lunge', 'lunge', 'dumbbell', 'c', [['glutes', 1], ['quads', .8], ['hamstrings', .4]]],
    ['step_up', 'Step-Up', 'lunge', 'dumbbell', 'c', [['quads', .9], ['glutes', .9], ['hamstrings', .3], ['calves', .25]]],
    ['smith_split_squat', 'Smith Machine Split Squat', 'lunge', 'machine', 'c', [['quads', 1], ['glutes', .8], ['adductors', .3]]],
    ['conventional_deadlift', 'Conventional Deadlift', 'hinge', 'barbell', 'c', [['hamstrings', 1], ['glutes', 1], ['erectors', .9], ['lats', .5], ['traps_upper', .5], ['forearms', .5], ['quads', .4]]],
    ['sumo_deadlift', 'Sumo Deadlift', 'hinge', 'barbell', 'c', [['glutes', 1], ['quads', .7], ['hamstrings', .7], ['erectors', .7], ['adductors', .6], ['traps_upper', .5], ['forearms', .5]]],
    ['trap_bar_deadlift', 'Trap Bar Deadlift', 'hinge', 'barbell', 'c', [['glutes', .9], ['quads', .8], ['hamstrings', .7], ['erectors', .7], ['traps_upper', .5], ['forearms', .5]]],
    ['romanian_deadlift', 'Romanian Deadlift (RDL)', 'hinge', 'barbell', 'c', [['hamstrings', 1], ['glutes', .8], ['erectors', .6], ['forearms', .4]]],
    ['stiff_leg_deadlift', 'Stiff-Leg Deadlift', 'hinge', 'barbell', 'c', [['hamstrings', 1], ['glutes', .7], ['erectors', .6]]],
    ['single_leg_rdl', 'Single-Leg RDL', 'hinge', 'dumbbell', 'c', [['hamstrings', 1], ['glutes', .9], ['erectors', .4], ['abductors', .3]]],
    ['good_morning', 'Good Morning', 'hinge', 'barbell', 'c', [['hamstrings', 1], ['erectors', .8], ['glutes', .7]]],
    ['hip_thrust', 'Barbell Hip Thrust', 'hinge', 'barbell', 'c', [['glutes', 1], ['hamstrings', .5], ['quads', .25]]],
    ['glute_bridge', 'Glute Bridge', 'hinge', 'barbell', 'c', [['glutes', 1], ['hamstrings', .4]]],
    ['back_extension', 'Back Extension / Hyperextension', 'hinge', 'bodyweight', 'c', [['erectors', 1], ['glutes', .7], ['hamstrings', .6]]],
    ['nordic_curl', 'Nordic Hamstring Curl', 'hinge', 'bodyweight', 'i', [['hamstrings', 1], ['glutes', .3]]],
    ['leg_curl_lying', 'Lying Leg Curl', 'hinge', 'machine', 'i', [['hamstrings', 1], ['calves', .25]]],
    ['leg_curl_seated', 'Seated Leg Curl', 'hinge', 'machine', 'i', [['hamstrings', 1]]],
    ['standing_leg_curl', 'Standing Leg Curl', 'hinge', 'machine', 'i', [['hamstrings', 1], ['calves', .25]]],
    ['kettlebell_swing', 'Kettlebell Swing', 'hinge', 'kettlebell', 'c', [['glutes', 1], ['hamstrings', .8], ['erectors', .5], ['forearms', .3]]],
    ['cable_pull_through', 'Cable Pull-Through', 'hinge', 'cable', 'c', [['glutes', 1], ['hamstrings', .6], ['erectors', .3]]],
    ['cable_hip_abduction', 'Cable Hip Abduction', 'hinge', 'cable', 'i', [['abductors', 1], ['glutes', .5]]],
    ['cable_glute_kickback', 'Cable Glute Kickback', 'hinge', 'cable', 'i', [['glutes', 1], ['hamstrings', .4]]],
    ['hip_thrust_machine', 'Hip Thrust Machine', 'hinge', 'machine', 'c', [['glutes', 1], ['hamstrings', .5], ['quads', .25]]],
    ['abductor_machine', 'Hip Abductor Machine', 'hinge', 'machine', 'i', [['abductors', 1], ['glutes', .5]]],
    ['adductor_machine', 'Hip Adductor Machine', 'hinge', 'machine', 'i', [['adductors', 1]]],
    ['glute_kickback_machine', 'Glute Kickback Machine', 'hinge', 'machine', 'i', [['glutes', 1], ['hamstrings', .4]]],
    ['reverse_hyper', 'Reverse Hyperextension', 'hinge', 'machine', 'c', [['glutes', 1], ['hamstrings', .7], ['erectors', .7]]],
    ['smith_rdl', 'Smith Machine RDL', 'hinge', 'machine', 'c', [['hamstrings', 1], ['glutes', .8], ['erectors', .5]]],
    ['barbell_bench_press', 'Barbell Bench Press', 'horizontal_push', 'barbell', 'c', [['chest_mid', 1], ['triceps', .6], ['delts_front', .6], ['chest_lower', .4]]],
    ['incline_barbell_press', 'Incline Barbell Bench Press', 'horizontal_push', 'barbell', 'c', [['chest_upper', 1], ['delts_front', .7], ['triceps', .5]]],
    ['decline_barbell_press', 'Decline Barbell Bench Press', 'horizontal_push', 'barbell', 'c', [['chest_lower', 1], ['triceps', .6], ['delts_front', .3]]],
    ['dumbbell_bench_press', 'Dumbbell Bench Press', 'horizontal_push', 'dumbbell', 'c', [['chest_mid', 1], ['delts_front', .5], ['triceps', .5]]],
    ['incline_dumbbell_press', 'Incline Dumbbell Press', 'horizontal_push', 'dumbbell', 'c', [['chest_upper', 1], ['delts_front', .6], ['triceps', .4]]],
    ['machine_chest_press', 'Machine Chest Press', 'horizontal_push', 'machine', 'c', [['chest_mid', 1], ['triceps', .5], ['delts_front', .4]]],
    ['smith_bench_press', 'Smith Machine Bench Press', 'horizontal_push', 'machine', 'c', [['chest_mid', 1], ['triceps', .5], ['delts_front', .4]]],
    ['floor_press', 'Floor Press', 'horizontal_push', 'barbell', 'c', [['chest_mid', .9], ['triceps', .8], ['delts_front', .4]]],
    ['push_up', 'Push-Up', 'horizontal_push', 'bodyweight', 'c', [['chest_mid', 1], ['triceps', .6], ['delts_front', .5], ['abs', .3]]],
    ['chest_dip', 'Chest Dip', 'horizontal_push', 'bodyweight', 'c', [['chest_lower', 1], ['triceps', .7], ['delts_front', .5]]],
    ['cable_fly', 'Cable Fly (mid)', 'horizontal_push', 'cable', 'i', [['chest_mid', 1], ['delts_front', .25]]],
    ['incline_fly', 'Incline Fly', 'horizontal_push', 'dumbbell', 'i', [['chest_upper', 1], ['delts_front', .3]]],
    ['pec_deck', 'Pec Deck / Machine Fly', 'horizontal_push', 'machine', 'i', [['chest_mid', 1]]],
    ['cable_chest_press', 'Standing Cable Chest Press', 'horizontal_push', 'cable', 'c', [['chest_mid', 1], ['triceps', .5], ['delts_front', .5], ['abs', .3]]],
    ['cable_fly_low_high', 'Low-to-High Cable Fly', 'horizontal_push', 'cable', 'i', [['chest_upper', 1], ['delts_front', .3]]],
    ['cable_fly_high_low', 'High-to-Low Cable Fly', 'horizontal_push', 'cable', 'i', [['chest_lower', 1], ['chest_mid', .5]]],
    ['incline_machine_press', 'Incline Machine Chest Press', 'horizontal_push', 'machine', 'c', [['chest_upper', 1], ['delts_front', .6], ['triceps', .5]]],
    ['decline_machine_press', 'Decline Machine Chest Press', 'horizontal_push', 'machine', 'c', [['chest_lower', 1], ['triceps', .5], ['delts_front', .3]]],
    ['converging_chest_press', 'Converging / Iso-Lateral Chest Press', 'horizontal_push', 'machine', 'c', [['chest_mid', 1], ['triceps', .5], ['delts_front', .4]]],
    ['smith_incline_press', 'Smith Machine Incline Press', 'horizontal_push', 'machine', 'c', [['chest_upper', 1], ['delts_front', .6], ['triceps', .5]]],
    ['overhead_press', 'Barbell Overhead Press', 'vertical_push', 'barbell', 'c', [['delts_front', 1], ['triceps', .6], ['delts_side', .5], ['abs', .4], ['traps_upper', .3]]],
    ['seated_db_shoulder_press', 'Seated Dumbbell Shoulder Press', 'vertical_push', 'dumbbell', 'c', [['delts_front', 1], ['delts_side', .6], ['triceps', .5]]],
    ['arnold_press', 'Arnold Press', 'vertical_push', 'dumbbell', 'c', [['delts_front', 1], ['delts_side', .7], ['triceps', .4]]],
    ['machine_shoulder_press', 'Machine Shoulder Press', 'vertical_push', 'machine', 'c', [['delts_front', 1], ['delts_side', .5], ['triceps', .5]]],
    ['push_press', 'Push Press', 'vertical_push', 'barbell', 'c', [['delts_front', 1], ['triceps', .6], ['quads', .4], ['delts_side', .4]]],
    ['landmine_press', 'Landmine Press', 'vertical_push', 'barbell', 'c', [['delts_front', 1], ['chest_upper', .5], ['triceps', .4], ['abs', .3]]],
    ['handstand_push_up', 'Handstand Push-Up', 'vertical_push', 'bodyweight', 'c', [['delts_front', 1], ['triceps', .8], ['delts_side', .5], ['traps_upper', .3]]],
    ['smith_overhead_press', 'Smith Machine Overhead Press', 'vertical_push', 'machine', 'c', [['delts_front', 1], ['triceps', .6], ['delts_side', .4]]],
    ['barbell_row', 'Barbell Bent-Over Row', 'horizontal_pull', 'barbell', 'c', [['lats', 1], ['rhomboids', .8], ['traps_mid_lower', .7], ['delts_rear', .5], ['biceps', .5], ['erectors', .5], ['forearms', .4]]],
    ['pendlay_row', 'Pendlay Row', 'horizontal_pull', 'barbell', 'c', [['lats', 1], ['rhomboids', .8], ['traps_mid_lower', .7], ['biceps', .5], ['erectors', .5]]],
    ['dumbbell_row', 'Single-Arm Dumbbell Row', 'horizontal_pull', 'dumbbell', 'c', [['lats', 1], ['rhomboids', .6], ['traps_mid_lower', .6], ['biceps', .5], ['delts_rear', .4], ['forearms', .4]]],
    ['seated_cable_row', 'Seated Cable Row', 'horizontal_pull', 'cable', 'c', [['lats', 1], ['rhomboids', .7], ['traps_mid_lower', .7], ['biceps', .5], ['delts_rear', .4]]],
    ['chest_supported_row', 'Chest-Supported Row', 'horizontal_pull', 'dumbbell', 'c', [['rhomboids', 1], ['traps_mid_lower', .9], ['lats', .8], ['delts_rear', .6], ['biceps', .4]]],
    ['t_bar_row', 'T-Bar Row', 'horizontal_pull', 'barbell', 'c', [['lats', 1], ['rhomboids', .8], ['traps_mid_lower', .7], ['biceps', .5], ['erectors', .4]]],
    ['inverted_row', 'Inverted Row', 'horizontal_pull', 'bodyweight', 'c', [['lats', .9], ['rhomboids', .9], ['traps_mid_lower', .7], ['biceps', .5], ['abs', .3]]],
    ['machine_row', 'Machine Row', 'horizontal_pull', 'machine', 'c', [['lats', 1], ['rhomboids', .7], ['traps_mid_lower', .6], ['biceps', .4]]],
    ['single_arm_cable_row', 'Single-Arm Cable Row', 'horizontal_pull', 'cable', 'c', [['lats', 1], ['rhomboids', .6], ['traps_mid_lower', .6], ['biceps', .5], ['delts_rear', .4], ['obliques', .25]]],
    ['iso_lateral_row', 'Iso-Lateral / Hammer Strength Row', 'horizontal_pull', 'machine', 'c', [['lats', 1], ['rhomboids', .7], ['traps_mid_lower', .6], ['biceps', .4], ['delts_rear', .4]]],
    ['machine_high_row', 'Machine High Row', 'horizontal_pull', 'machine', 'c', [['lats', 1], ['rhomboids', .6], ['delts_rear', .5], ['biceps', .4]]],
    ['machine_low_row', 'Machine Low Row', 'horizontal_pull', 'machine', 'c', [['lats', 1], ['traps_mid_lower', .7], ['rhomboids', .6], ['biceps', .4]]],
    ['face_pull', 'Face Pull', 'horizontal_pull', 'cable', 'i', [['delts_rear', 1], ['traps_mid_lower', .6], ['rotator_cuff', .6], ['rhomboids', .4]]],
    ['rear_delt_fly', 'Rear Delt Fly / Reverse Pec Deck', 'horizontal_pull', 'machine', 'i', [['delts_rear', 1], ['rhomboids', .5], ['traps_mid_lower', .4]]],
    ['cable_rear_delt_fly', 'Cable Rear Delt Fly', 'horizontal_pull', 'cable', 'i', [['delts_rear', 1], ['traps_mid_lower', .5], ['rhomboids', .4]]],
    ['pull_up', 'Pull-Up', 'vertical_pull', 'bodyweight', 'c', [['lats', 1], ['biceps', .6], ['teres', .6], ['rhomboids', .5], ['brachialis', .4], ['forearms', .4], ['abs', .3]]],
    ['chin_up', 'Chin-Up', 'vertical_pull', 'bodyweight', 'c', [['lats', 1], ['biceps', .8], ['teres', .5], ['brachialis', .4], ['abs', .3]]],
    ['assisted_pull_up', 'Assisted Pull-Up', 'vertical_pull', 'machine', 'c', [['lats', 1], ['biceps', .6], ['teres', .5]]],
    ['lat_pulldown', 'Lat Pulldown (wide)', 'vertical_pull', 'cable', 'c', [['lats', 1], ['teres', .6], ['biceps', .5], ['rhomboids', .4]]],
    ['neutral_pulldown', 'Neutral-Grip Pulldown', 'vertical_pull', 'cable', 'c', [['lats', 1], ['biceps', .6], ['brachialis', .4], ['teres', .5]]],
    ['straight_arm_pulldown', 'Straight-Arm Pulldown', 'vertical_pull', 'cable', 'i', [['lats', 1], ['teres', .4], ['abs', .25]]],
    ['cable_pullover', 'Cable Pullover', 'vertical_pull', 'cable', 'i', [['lats', 1], ['teres', .5], ['triceps', .3]]],
    ['machine_lat_pulldown', 'Plate-Loaded Lat Pulldown', 'vertical_pull', 'machine', 'c', [['lats', 1], ['teres', .6], ['biceps', .5], ['rhomboids', .4]]],
    ['machine_pullover', 'Machine Pullover', 'vertical_pull', 'machine', 'i', [['lats', 1], ['teres', .5], ['triceps', .3]]],
    ['lateral_raise', 'Dumbbell Lateral Raise', 'shoulder_iso', 'dumbbell', 'i', [['delts_side', 1], ['traps_upper', .25]]],
    ['cable_lateral_raise', 'Cable Lateral Raise', 'shoulder_iso', 'cable', 'i', [['delts_side', 1]]],
    ['front_raise', 'Front Raise', 'shoulder_iso', 'dumbbell', 'i', [['delts_front', 1], ['chest_upper', .25]]],
    ['upright_row', 'Upright Row', 'shoulder_iso', 'barbell', 'c', [['delts_side', 1], ['traps_upper', .7], ['biceps', .3]]],
    ['shrug', 'Barbell / Dumbbell Shrug', 'shoulder_iso', 'barbell', 'i', [['traps_upper', 1], ['forearms', .4]]],
    ['cable_upright_row', 'Cable Upright Row', 'shoulder_iso', 'cable', 'c', [['delts_side', 1], ['traps_upper', .6], ['biceps', .25]]],
    ['cable_front_raise', 'Cable Front Raise', 'shoulder_iso', 'cable', 'i', [['delts_front', 1], ['chest_upper', .25]]],
    ['cable_y_raise', 'Cable Y-Raise', 'shoulder_iso', 'cable', 'i', [['delts_side', .9], ['traps_mid_lower', .8], ['delts_rear', .5], ['rotator_cuff', .4]]],
    ['cable_external_rotation', 'Cable External Rotation', 'shoulder_iso', 'cable', 'i', [['rotator_cuff', 1], ['delts_rear', .4]]],
    ['cable_shrug', 'Cable Shrug', 'shoulder_iso', 'cable', 'i', [['traps_upper', 1], ['forearms', .3]]],
    ['machine_lateral_raise', 'Machine Lateral Raise', 'shoulder_iso', 'machine', 'i', [['delts_side', 1], ['traps_upper', .25]]],
    ['smith_shrug', 'Smith Machine Shrug', 'shoulder_iso', 'machine', 'i', [['traps_upper', 1], ['forearms', .3]]],
    ['barbell_curl', 'Barbell Curl', 'biceps', 'barbell', 'i', [['biceps', 1], ['brachialis', .5], ['forearms', .3]]],
    ['dumbbell_curl', 'Dumbbell Curl', 'biceps', 'dumbbell', 'i', [['biceps', 1], ['brachialis', .4], ['forearms', .3]]],
    ['hammer_curl', 'Hammer Curl', 'biceps', 'dumbbell', 'i', [['brachialis', 1], ['biceps', .7], ['forearms', .5]]],
    ['preacher_curl', 'Preacher Curl', 'biceps', 'barbell', 'i', [['biceps', 1], ['brachialis', .4]]],
    ['incline_db_curl', 'Incline Dumbbell Curl', 'biceps', 'dumbbell', 'i', [['biceps', 1], ['brachialis', .3]]],
    ['cable_curl', 'Cable Curl', 'biceps', 'cable', 'i', [['biceps', 1], ['brachialis', .4], ['forearms', .3]]],
    ['concentration_curl', 'Concentration Curl', 'biceps', 'dumbbell', 'i', [['biceps', 1]]],
    ['cable_hammer_curl', 'Cable Rope Hammer Curl', 'biceps', 'cable', 'i', [['brachialis', 1], ['biceps', .7], ['forearms', .5]]],
    ['cable_preacher_curl', 'Cable Preacher Curl', 'biceps', 'cable', 'i', [['biceps', 1], ['brachialis', .4]]],
    ['bayesian_curl', 'Bayesian Cable Curl', 'biceps', 'cable', 'i', [['biceps', 1], ['brachialis', .3]]],
    ['machine_preacher_curl', 'Machine Preacher Curl', 'biceps', 'machine', 'i', [['biceps', 1], ['brachialis', .4]]],
    ['machine_bicep_curl', 'Machine Biceps Curl', 'biceps', 'machine', 'i', [['biceps', 1], ['brachialis', .4]]],
    ['close_grip_bench', 'Close-Grip Bench Press', 'triceps', 'barbell', 'c', [['triceps', 1], ['chest_mid', .6], ['delts_front', .4]]],
    ['triceps_pushdown', 'Cable Triceps Pushdown', 'triceps', 'cable', 'i', [['triceps', 1]]],
    ['overhead_triceps_ext', 'Overhead Triceps Extension', 'triceps', 'dumbbell', 'i', [['triceps', 1]]],
    ['skullcrusher', 'Skullcrusher', 'triceps', 'barbell', 'i', [['triceps', 1]]],
    ['triceps_dip', 'Triceps Dip', 'triceps', 'bodyweight', 'c', [['triceps', 1], ['chest_lower', .6], ['delts_front', .4]]],
    ['triceps_kickback', 'Triceps Kickback', 'triceps', 'dumbbell', 'i', [['triceps', 1]]],
    ['cable_overhead_triceps_ext', 'Cable Overhead Triceps Extension', 'triceps', 'cable', 'i', [['triceps', 1]]],
    ['cable_reverse_pushdown', 'Reverse-Grip Cable Pushdown', 'triceps', 'cable', 'i', [['triceps', 1], ['forearms', .3]]],
    ['single_arm_pushdown', 'Single-Arm Cable Pushdown', 'triceps', 'cable', 'i', [['triceps', 1]]],
    ['cable_kickback', 'Cable Triceps Kickback', 'triceps', 'cable', 'i', [['triceps', 1]]],
    ['machine_triceps_extension', 'Machine Triceps Extension', 'triceps', 'machine', 'i', [['triceps', 1]]],
    ['assisted_dip_machine', 'Assisted Dip Machine', 'triceps', 'machine', 'c', [['triceps', 1], ['chest_lower', .6], ['delts_front', .4]]],
    ['standing_calf_raise', 'Standing Calf Raise', 'calves', 'machine', 'i', [['calves', 1]]],
    ['seated_calf_raise', 'Seated Calf Raise', 'calves', 'machine', 'i', [['calves', 1]]],
    ['leg_press_calf_raise', 'Leg Press Calf Raise', 'calves', 'machine', 'i', [['calves', 1]]],
    ['donkey_calf_raise', 'Donkey Calf Raise', 'calves', 'machine', 'i', [['calves', 1]]],
    ['smith_calf_raise', 'Smith Machine Calf Raise', 'calves', 'machine', 'i', [['calves', 1]]],
    ['plank', 'Plank', 'core', 'bodyweight', 'i', [['abs', 1], ['obliques', .5]]],
    ['hanging_leg_raise', 'Hanging Leg Raise', 'core', 'bodyweight', 'c', [['abs', 1], ['hip_flexors', .7], ['forearms', .4], ['obliques', .3]]],
    ['cable_crunch', 'Cable Crunch', 'core', 'cable', 'i', [['abs', 1], ['obliques', .3]]],
    ['ab_wheel', 'Ab Wheel Rollout', 'core', 'bodyweight', 'c', [['abs', 1], ['obliques', .4], ['lats', .3]]],
    ['russian_twist', 'Russian Twist', 'core', 'dumbbell', 'i', [['obliques', 1], ['abs', .6]]],
    ['sit_up', 'Sit-Up / Crunch', 'core', 'bodyweight', 'i', [['abs', 1], ['hip_flexors', .4]]],
    ['pallof_press', 'Pallof Press', 'core', 'cable', 'i', [['obliques', 1], ['abs', .6]]],
    ['side_plank', 'Side Plank', 'core', 'bodyweight', 'i', [['obliques', 1], ['abs', .4]]],
    ['cable_woodchopper', 'Cable Woodchopper', 'core', 'cable', 'c', [['obliques', 1], ['abs', .6], ['delts_front', .25]]],
    ['cable_side_bend', 'Cable Side Bend', 'core', 'cable', 'i', [['obliques', 1], ['erectors', .3]]],
    ['ab_crunch_machine', 'Ab Crunch Machine', 'core', 'machine', 'i', [['abs', 1], ['obliques', .3]]],
    ['torso_rotation_machine', 'Torso Rotation Machine', 'core', 'machine', 'i', [['obliques', 1], ['abs', .4]]],
    ['captains_chair_leg_raise', "Captain's Chair Leg Raise", 'core', 'machine', 'c', [['abs', 1], ['hip_flexors', .7], ['obliques', .3]]],
    ['wrist_curl', 'Wrist Curl / Reverse Wrist Curl', 'forearms', 'dumbbell', 'i', [['forearms', 1]]],
    ['farmers_carry', "Farmer's Carry", 'carry', 'dumbbell', 'c', [['forearms', 1], ['traps_upper', .7], ['abs', .5], ['obliques', .4], ['erectors', .4]]]
  ];
  var exercises = E.map(function (r) {
    return {
      id: r[0], name: r[1], pattern: r[2], equipment: r[3],
      mechanic: r[4] === 'c' ? 'compound' : 'isolation',
      muscles: r[5].map(function (m) {
        return { muscle: m[0], contribution: m[1], role: m[1] >= 0.8 ? 'primary' : (m[1] >= 0.4 ? 'secondary' : 'stabilizer') };
      })
    };
  });
  var byId = {}, byName = {};
  exercises.forEach(function (e) { byId[e.id] = e; byName[e.name.toLowerCase()] = e; });
  window.MOVEMENT_DB = {
    muscles: M, patterns: PATTERNS, patternOrder: PATTERN_ORDER,
    exercises: exercises, byId: byId, byName: byName
  };
})();
